# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/http-cookie/all/http-cookie.rbi
#
# http-cookie-1.1.6

class HTTP::CookieJar
  def <<(cookie); end
  def add(cookie); end
  def cleanup(session = nil); end
  def clear; end
  def cookies(url = nil); end
  def delete(cookie); end
  def each(uri = nil, &block); end
  def empty?(url = nil); end
  def get_impl(base, value, *args); end
  def initialize(options = nil); end
  def initialize_copy(other); end
  def load(readable, *options); end
  def parse(set_cookie, origin, options = nil); end
  def save(writable, *options); end
  def store; end
  include Enumerable
end
class HTTP::CookieJar::HashStore < HTTP::CookieJar::AbstractStore
  def add(cookie); end
  def cleanup(session = nil); end
  def clear; end
  def default_options; end
  def delete(cookie); end
  def each(uri = nil); end
  def initialize(options = nil); end
  def initialize_copy(other); end
end
class HTTP::CookieJar::MozillaStore < HTTP::CookieJar::AbstractStore
  def add(cookie); end
  def cleanup(session = nil); end
  def clear; end
  def close; end
  def closed?; end
  def create_table; end
  def create_table_v5; end
  def create_table_v6; end
  def db_add(cookie); end
  def db_delete(cookie); end
  def db_prepare(sql); end
  def default_options; end
  def delete(cookie); end
  def deserialize_usectime(value); end
  def each(uri = nil, &block); end
  def encode_www_form(enum); end
  def filename; end
  def get_query_param(str, key); end
  def initialize(options = nil); end
  def initialize_copy(other); end
  def schema_version; end
  def schema_version=(version); end
  def serialize_usectime(time); end
  def upgrade_database; end
end
class HTTP::CookieJar::MozillaStore::Database
  def close; end
  def closed?; end
  def create_function(*args, &block); end
  def execute(*args, &block); end
  def initialize(file); end
  def prepare(sql); end
end
class HTTP::CookieJar::AbstractStore
  def add(cookie); end
  def cleanup(session = nil); end
  def clear; end
  def default_options; end
  def delete(cookie); end
  def each(uri = nil, &block); end
  def empty?; end
  def initialize(options = nil); end
  def initialize_copy(other); end
  def self.implementation(symbol); end
  include Enumerable
  include MonitorMixin
end
class HTTP::CookieJar::YAMLSaver < HTTP::CookieJar::AbstractSaver
  def default_options; end
  def load(io, jar); end
  def load_yaml(yaml); end
  def save(io, jar); end
end
class HTTP::CookieJar::CookiestxtSaver < HTTP::CookieJar::AbstractSaver
  def cookie_to_record(cookie); end
  def default_options; end
  def load(io, jar); end
  def parse_record(line); end
  def save(io, jar); end
end
class HTTP::CookieJar::AbstractSaver
  def default_options; end
  def initialize(options = nil); end
  def load(io, jar); end
  def save(io, jar); end
  def self.implementation(symbol); end
end
module HTTP
end
