# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec_junit_formatter` gem.
# Please instead update this file by running `bin/tapioca gem rspec_junit_formatter`.


# Dumps rspec results as a JUnit XML file.
# Based on XML schema: http://windyroad.org/dl/Open%20Source/JUnit.xsd
#
# pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:11
class RSpecJUnitFormatter < ::RSpec::Core::Formatters::BaseFormatter
  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:19
  def dump_summary(notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:9
  def start(notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:15
  def stop(notification); end

  private

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:69
  def classname_for(notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:78
  def description_for(notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:40
  def duration; end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:74
  def duration_for(notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:48
  def error_count; end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:167
  def escape(text); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:28
  def example_count; end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:61
  def example_group_file_path_for(notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:44
  def examples; end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:94
  def exception_for(notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:36
  def failure_count; end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:90
  def failure_for(notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:86
  def failure_message_for(example); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:82
  def failure_type_for(example); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:32
  def pending_count; end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:57
  def result_of(notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:26
  def started; end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:141
  def stderr_for(example_notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:137
  def stdout_for(example_notification); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:175
  def strip_diff_colors(string); end

  # rspec makes it really difficult to swap in configuration temporarily due to
  # the way it cascades defaults, command line arguments, and user
  # configuration. This method makes sure configuration gets swapped in
  # correctly, but also that the original state is definitely restored.
  #
  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:102
  def swap_rspec_configuration(key, value); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter/rspec3.rb:123
  def without_color(&block); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:16
  def xml_dump; end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:68
  def xml_dump_example(example); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:38
  def xml_dump_examples; end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:57
  def xml_dump_failed(example); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:82
  def xml_dump_output(example); end

  # pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:51
  def xml_dump_pending(example); end
end

# Discouraged characters from https://www.w3.org/TR/xml/#charsets
# Plus special characters with well-known entity replacements
#
# pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:129
RSpecJUnitFormatter::DISCOURAGED_REGEXP = T.let(T.unsafe(nil), Regexp)

# Translate well-known entities, or use generic unicode hex entity
#
# pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:159
RSpecJUnitFormatter::DISCOURAGED_REPLACEMENTS = T.let(T.unsafe(nil), Hash)

# Inversion of character range from https://www.w3.org/TR/xml/#charsets
#
# pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:97
RSpecJUnitFormatter::ILLEGAL_REGEXP = T.let(T.unsafe(nil), Regexp)

# Replace illegals with a Ruby-like escape
#
# pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:109
RSpecJUnitFormatter::ILLEGAL_REPLACEMENT = T.let(T.unsafe(nil), Hash)

# pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:172
RSpecJUnitFormatter::STRIP_DIFF_COLORS_BLOCK_REGEXP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:173
RSpecJUnitFormatter::STRIP_DIFF_COLORS_CODES_REGEXP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rspec_junit_formatter#lib/rspec_junit_formatter.rb:189
RspecJunitFormatter = RSpecJUnitFormatter
