# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby_llm/all/ruby_llm.rbi
#
# ruby_llm-1.14.1

module RubyLLM
  def self.chat(*, **, &); end
  def self.config; end
  def self.configure; end
  def self.context; end
  def self.embed(*, **, &); end
  def self.logger; end
  def self.models; end
  def self.moderate(*, **, &); end
  def self.paint(*, **, &); end
  def self.providers; end
  def self.transcribe(*, **, &); end
end
class RubyLLM::Error < StandardError
  def initialize(response = nil, message = nil); end
  def response; end
end
class RubyLLM::ConfigurationError < StandardError
end
class RubyLLM::PromptNotFoundError < StandardError
end
class RubyLLM::InvalidRoleError < StandardError
end
class RubyLLM::InvalidToolChoiceError < StandardError
end
class RubyLLM::ModelNotFoundError < StandardError
end
class RubyLLM::UnsupportedAttachmentError < StandardError
end
class RubyLLM::BadRequestError < RubyLLM::Error
end
class RubyLLM::ForbiddenError < RubyLLM::Error
end
class RubyLLM::ContextLengthExceededError < RubyLLM::Error
end
class RubyLLM::OverloadedError < RubyLLM::Error
end
class RubyLLM::PaymentRequiredError < RubyLLM::Error
end
class RubyLLM::RateLimitError < RubyLLM::Error
end
class RubyLLM::ServerError < RubyLLM::Error
end
class RubyLLM::ServiceUnavailableError < RubyLLM::Error
end
class RubyLLM::UnauthorizedError < RubyLLM::Error
end
class RubyLLM::ErrorMiddleware < Faraday::Middleware
  def call(env); end
  def initialize(app, options = nil); end
  def self.context_length_exceeded?(message); end
  def self.parse_error(provider:, response:); end
end
module RubyLLM::Streaming
  def build_on_data_handler(&handler); end
  def build_stream_error_response(parsed_data, env, status); end
  def error_chunk?(chunk); end
  def faraday_1?; end
  def handle_data(data, env); end
  def handle_error_chunk(chunk, env); end
  def handle_error_event(data, env); end
  def handle_failed_response(chunk, buffer, env); end
  def handle_json_error_chunk(chunk, env); end
  def handle_parsed_error(parsed_data, env); end
  def handle_sse(chunk, parser, env, &block); end
  def handle_stream(&block); end
  def json_error_payload?(chunk); end
  def parse_error_from_json(data, env, error_message); end
  def parse_streaming_error(data); end
  def process_stream_chunk(chunk, parser, env, &); end
  def self.handle_stream(&block); end
  def self.stream_response(connection, payload, additional_headers = nil, &block); end
  def stream_response(connection, payload, additional_headers = nil, &block); end
end
module RubyLLM::Streaming::FaradayHandlers
  def build(faraday_v1:, on_chunk:, on_failed_response:); end
  def self.build(faraday_v1:, on_chunk:, on_failed_response:); end
  def self.v1_on_data(on_chunk); end
  def self.v2_on_data(on_chunk, on_failed_response); end
  def v1_on_data(on_chunk); end
  def v2_on_data(on_chunk, on_failed_response); end
end
class RubyLLM::Provider
  def api_base; end
  def assume_models_exist?; end
  def build_audio_file_part(file_path); end
  def capabilities; end
  def complete(messages, tools:, temperature:, model:, params: nil, headers: nil, schema: nil, thinking: nil, tool_prefs: nil, &); end
  def config; end
  def configuration_requirements; end
  def configured?; end
  def connection; end
  def embed(text, model:, dimensions:); end
  def ensure_configured!; end
  def format_messages(messages); end
  def format_tool_calls(_tool_calls); end
  def headers; end
  def initialize(config); end
  def list_models; end
  def local?; end
  def maybe_normalize_temperature(temperature, _model); end
  def moderate(input, model:); end
  def name; end
  def paint(prompt, model:, size:); end
  def parse_error(response); end
  def parse_tool_calls(_tool_calls); end
  def remote?; end
  def self.assume_models_exist?; end
  def self.capabilities; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  def self.configured?(config); end
  def self.configured_providers(config); end
  def self.configured_remote_providers(config); end
  def self.for(model); end
  def self.local?; end
  def self.local_providers; end
  def self.name; end
  def self.providers; end
  def self.register(name, provider_class); end
  def self.remote?; end
  def self.remote_providers; end
  def self.resolve(name); end
  def self.slug; end
  def slug; end
  def sync_response(connection, payload, additional_headers = nil); end
  def transcribe(audio_file, model:, language:, **options); end
  def try_parse_json(maybe_json); end
  include RubyLLM::Streaming
end
module RubyLLM::Providers
end
class RubyLLM::Providers::Anthropic < RubyLLM::Provider
  def api_base; end
  def headers; end
  def self.capabilities; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  include RubyLLM::Providers::Anthropic::Chat
  include RubyLLM::Providers::Anthropic::Embeddings
  include RubyLLM::Providers::Anthropic::Media
  include RubyLLM::Providers::Anthropic::Models
  include RubyLLM::Providers::Anthropic::Streaming
  include RubyLLM::Providers::Anthropic::Tools
end
module RubyLLM::Providers::Anthropic::Chat
  def add_optional_fields(payload, system_content:, tools:, tool_prefs:, temperature:, schema: nil); end
  def append_formatted_content(content_blocks, content); end
  def build_base_payload(chat_messages, model, stream, thinking); end
  def build_message(data, content, thinking, thinking_signature, tool_use_blocks, response); end
  def build_output_config(schema); end
  def build_system_content(system_messages); end
  def build_thinking_block(thinking); end
  def build_thinking_payload(thinking); end
  def completion_url; end
  def convert_role(role); end
  def extract_text_content(blocks); end
  def extract_thinking_content(blocks); end
  def extract_thinking_signature(blocks); end
  def format_basic_message_with_thinking(msg, thinking_enabled); end
  def format_message(msg, thinking: nil); end
  def format_tool_call_with_thinking(msg, thinking_enabled); end
  def parse_completion_response(response); end
  def prepend_thinking_block(content_blocks, msg, thinking_enabled); end
  def render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def resolve_budget(thinking); end
  def self.add_optional_fields(payload, system_content:, tools:, tool_prefs:, temperature:, schema: nil); end
  def self.append_formatted_content(content_blocks, content); end
  def self.build_base_payload(chat_messages, model, stream, thinking); end
  def self.build_message(data, content, thinking, thinking_signature, tool_use_blocks, response); end
  def self.build_output_config(schema); end
  def self.build_system_content(system_messages); end
  def self.build_thinking_block(thinking); end
  def self.build_thinking_payload(thinking); end
  def self.completion_url; end
  def self.convert_role(role); end
  def self.extract_text_content(blocks); end
  def self.extract_thinking_content(blocks); end
  def self.extract_thinking_signature(blocks); end
  def self.format_basic_message_with_thinking(msg, thinking_enabled); end
  def self.format_message(msg, thinking: nil); end
  def self.format_tool_call_with_thinking(msg, thinking_enabled); end
  def self.parse_completion_response(response); end
  def self.prepend_thinking_block(content_blocks, msg, thinking_enabled); end
  def self.render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def self.resolve_budget(thinking); end
  def self.separate_messages(messages); end
  def separate_messages(messages); end
end
module RubyLLM::Providers::Anthropic::Embeddings
  def embed; end
  def embedding_url; end
  def parse_embedding_response; end
  def render_embedding_payload; end
end
module RubyLLM::Providers::Anthropic::Media
  def format_content(content); end
  def format_image(image); end
  def format_pdf(pdf); end
  def format_text(text); end
  def format_text_file(text_file); end
  def self.format_content(content); end
  def self.format_image(image); end
  def self.format_pdf(pdf); end
  def self.format_text(text); end
  def self.format_text_file(text_file); end
end
module RubyLLM::Providers::Anthropic::Models
  def extract_cache_creation_tokens(data); end
  def extract_cached_tokens(data); end
  def extract_input_tokens(data); end
  def extract_model_id(data); end
  def extract_output_tokens(data); end
  def models_url; end
  def parse_list_models_response(response, slug, _capabilities); end
  def self.extract_cache_creation_tokens(data); end
  def self.extract_cached_tokens(data); end
  def self.extract_input_tokens(data); end
  def self.extract_model_id(data); end
  def self.extract_output_tokens(data); end
  def self.models_url; end
  def self.parse_list_models_response(response, slug, _capabilities); end
end
module RubyLLM::Providers::Anthropic::Streaming
  def build_chunk(data); end
  def extract_content_delta(data, delta_type); end
  def extract_signature_delta(data, delta_type); end
  def extract_thinking_delta(data, delta_type); end
  def json_delta?(data); end
  def parse_streaming_error(data); end
  def stream_url; end
end
module RubyLLM::Providers::Anthropic::Tools
  def build_tool_choice(tool_prefs); end
  def default_input_schema; end
  def extract_tool_calls(data); end
  def find_tool_uses(blocks); end
  def format_tool_call(msg); end
  def format_tool_result(msg); end
  def format_tool_result_block(msg); end
  def format_tool_use_block(tool_call); end
  def function_for(tool); end
  def parse_tool_calls(content_blocks); end
  def self.build_tool_choice(tool_prefs); end
  def self.default_input_schema; end
  def self.extract_tool_calls(data); end
  def self.find_tool_uses(blocks); end
  def self.format_tool_call(msg); end
  def self.format_tool_result(msg); end
  def self.format_tool_result_block(msg); end
  def self.format_tool_use_block(tool_call); end
  def self.function_for(tool); end
  def self.parse_tool_calls(content_blocks); end
end
class RubyLLM::Configuration
  def anthropic_api_base; end
  def anthropic_api_base=(arg0); end
  def anthropic_api_key; end
  def anthropic_api_key=(arg0); end
  def azure_ai_auth_token; end
  def azure_ai_auth_token=(arg0); end
  def azure_api_base; end
  def azure_api_base=(arg0); end
  def azure_api_key; end
  def azure_api_key=(arg0); end
  def bedrock_api_key; end
  def bedrock_api_key=(arg0); end
  def bedrock_region; end
  def bedrock_region=(arg0); end
  def bedrock_secret_key; end
  def bedrock_secret_key=(arg0); end
  def bedrock_session_token; end
  def bedrock_session_token=(arg0); end
  def deepseek_api_base; end
  def deepseek_api_base=(arg0); end
  def deepseek_api_key; end
  def deepseek_api_key=(arg0); end
  def default_embedding_model; end
  def default_embedding_model=(arg0); end
  def default_image_model; end
  def default_image_model=(arg0); end
  def default_model; end
  def default_model=(arg0); end
  def default_moderation_model; end
  def default_moderation_model=(arg0); end
  def default_transcription_model; end
  def default_transcription_model=(arg0); end
  def gemini_api_base; end
  def gemini_api_base=(arg0); end
  def gemini_api_key; end
  def gemini_api_key=(arg0); end
  def gpustack_api_base; end
  def gpustack_api_base=(arg0); end
  def gpustack_api_key; end
  def gpustack_api_key=(arg0); end
  def http_proxy; end
  def http_proxy=(arg0); end
  def initialize; end
  def instance_variables; end
  def log_file; end
  def log_file=(arg0); end
  def log_level; end
  def log_level=(arg0); end
  def log_regexp_timeout; end
  def log_regexp_timeout=(value); end
  def log_stream_debug; end
  def log_stream_debug=(arg0); end
  def logger; end
  def logger=(arg0); end
  def max_retries; end
  def max_retries=(arg0); end
  def mistral_api_key; end
  def mistral_api_key=(arg0); end
  def model_registry_class; end
  def model_registry_class=(arg0); end
  def model_registry_file; end
  def model_registry_file=(arg0); end
  def ollama_api_base; end
  def ollama_api_base=(arg0); end
  def ollama_api_key; end
  def ollama_api_key=(arg0); end
  def openai_api_base; end
  def openai_api_base=(arg0); end
  def openai_api_key; end
  def openai_api_key=(arg0); end
  def openai_organization_id; end
  def openai_organization_id=(arg0); end
  def openai_project_id; end
  def openai_project_id=(arg0); end
  def openai_use_system_role; end
  def openai_use_system_role=(arg0); end
  def openrouter_api_base; end
  def openrouter_api_base=(arg0); end
  def openrouter_api_key; end
  def openrouter_api_key=(arg0); end
  def perplexity_api_key; end
  def perplexity_api_key=(arg0); end
  def request_timeout; end
  def request_timeout=(arg0); end
  def retry_backoff_factor; end
  def retry_backoff_factor=(arg0); end
  def retry_interval; end
  def retry_interval=(arg0); end
  def retry_interval_randomness; end
  def retry_interval_randomness=(arg0); end
  def self.defaults; end
  def self.option(key, default = nil); end
  def self.option_keys; end
  def self.options; end
  def self.register_provider_options(options); end
  def use_new_acts_as; end
  def use_new_acts_as=(arg0); end
  def vertexai_location; end
  def vertexai_location=(arg0); end
  def vertexai_project_id; end
  def vertexai_project_id=(arg0); end
  def vertexai_service_account_key; end
  def vertexai_service_account_key=(arg0); end
  def xai_api_key; end
  def xai_api_key=(arg0); end
end
class RubyLLM::Providers::OpenAI < RubyLLM::Provider
  def api_base; end
  def headers; end
  def maybe_normalize_temperature(temperature, model); end
  def self.capabilities; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  include RubyLLM::Providers::OpenAI::Chat
  include RubyLLM::Providers::OpenAI::Embeddings
  include RubyLLM::Providers::OpenAI::Images
  include RubyLLM::Providers::OpenAI::Media
  include RubyLLM::Providers::OpenAI::Models
  include RubyLLM::Providers::OpenAI::Moderation
  include RubyLLM::Providers::OpenAI::Streaming
  include RubyLLM::Providers::OpenAI::Tools
  include RubyLLM::Providers::OpenAI::Transcription
end
module RubyLLM::Providers::OpenAI::Chat
  def completion_url; end
  def extract_content_and_thinking(content); end
  def extract_text_from_blocks(blocks); end
  def extract_think_tag_content(text); end
  def extract_thinking_from_blocks(blocks); end
  def extract_thinking_signature(message_data); end
  def extract_thinking_text(message_data); end
  def extract_thinking_text_from_block(block); end
  def format_messages(messages); end
  def format_role(role); end
  def format_thinking(msg); end
  def parse_completion_response(response); end
  def render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def resolve_effort(thinking); end
  def self.extract_content_and_thinking(content); end
  def self.extract_text_from_blocks(blocks); end
  def self.extract_think_tag_content(text); end
  def self.extract_thinking_from_blocks(blocks); end
  def self.extract_thinking_signature(message_data); end
  def self.extract_thinking_text(message_data); end
  def self.extract_thinking_text_from_block(block); end
  def self.format_messages(messages); end
  def self.format_role(role); end
  def self.format_thinking(msg); end
  def self.parse_completion_response(response); end
  def self.render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def self.resolve_effort(thinking); end
end
module RubyLLM::Providers::OpenAI::Embeddings
  def embedding_url(*, **, &); end
  def parse_embedding_response(response, model:, text:); end
  def render_embedding_payload(text, model:, dimensions:); end
  def self.embedding_url(*, **, &); end
  def self.parse_embedding_response(response, model:, text:); end
  def self.render_embedding_payload(text, model:, dimensions:); end
end
module RubyLLM::Providers::OpenAI::Models
  def models_url; end
  def parse_list_models_response(response, slug, capabilities); end
  def self.models_url; end
  def self.parse_list_models_response(response, slug, capabilities); end
end
module RubyLLM::Providers::OpenAI::Moderation
  def moderation_url; end
  def parse_moderation_response(response, model:); end
  def render_moderation_payload(input, model:); end
  def self.moderation_url; end
  def self.parse_moderation_response(response, model:); end
  def self.render_moderation_payload(input, model:); end
end
module RubyLLM::Providers::OpenAI::Streaming
  def build_chunk(data); end
  def parse_streaming_error(data); end
  def self.build_chunk(data); end
  def self.parse_streaming_error(data); end
  def self.stream_url; end
  def stream_url; end
end
module RubyLLM::Providers::OpenAI::Tools
  def build_tool_choice(tool_choice); end
  def extract_tool_call_thought_signature(tool_call); end
  def format_tool_calls(tool_calls); end
  def param_schema(param); end
  def parameters_schema_for(tool); end
  def parse_tool_call_arguments(tool_call); end
  def parse_tool_calls(tool_calls, parse_arguments: nil); end
  def schema_from_parameters(parameters); end
  def self.build_tool_choice(tool_choice); end
  def self.extract_tool_call_thought_signature(tool_call); end
  def self.format_tool_calls(tool_calls); end
  def self.param_schema(param); end
  def self.parameters_schema_for(tool); end
  def self.parse_tool_call_arguments(tool_call); end
  def self.parse_tool_calls(tool_calls, parse_arguments: nil); end
  def self.schema_from_parameters(parameters); end
  def self.tool_for(tool); end
  def tool_for(tool); end
end
module RubyLLM::Providers::OpenAI::Images
  def images_url; end
  def parse_image_response(response, model:); end
  def render_image_payload(prompt, model:, size:); end
  def self.images_url; end
  def self.parse_image_response(response, model:); end
  def self.render_image_payload(prompt, model:, size:); end
end
module RubyLLM::Providers::OpenAI::Media
  def format_audio(audio); end
  def format_content(content); end
  def format_image(image); end
  def format_pdf(pdf); end
  def format_text(text); end
  def format_text_file(text_file); end
  def self.format_audio(audio); end
  def self.format_content(content); end
  def self.format_image(image); end
  def self.format_pdf(pdf); end
  def self.format_text(text); end
  def self.format_text_file(text_file); end
end
module RubyLLM::Providers::OpenAI::Transcription
  def encode_speaker_references(references); end
  def parse_transcription_response(response, model:); end
  def render_transcription_payload(file_part, model:, language:, **options); end
  def response_format_for(model, options); end
  def self.encode_speaker_references(references); end
  def self.parse_transcription_response(response, model:); end
  def self.render_transcription_payload(file_part, model:, language:, **options); end
  def self.response_format_for(model, options); end
  def self.supports_chunking_strategy?(model, options); end
  def self.transcription_url; end
  def supports_chunking_strategy?(model, options); end
  def transcription_url; end
end
class RubyLLM::Providers::Azure < RubyLLM::Providers::OpenAI
  def api_base; end
  def azure_base_parts; end
  def azure_endpoint(kind); end
  def azure_host_root(base_without_query); end
  def chat_endpoint(parts); end
  def configured?; end
  def embeddings_endpoint(parts); end
  def ensure_configured!; end
  def headers; end
  def models_endpoint(parts); end
  def self.assume_models_exist?; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  def self.configured?(config); end
  def with_api_version(path, version); end
  include RubyLLM::Providers::Azure::Chat
  include RubyLLM::Providers::Azure::Embeddings
  include RubyLLM::Providers::Azure::Media
  include RubyLLM::Providers::Azure::Models
end
module RubyLLM::Providers::Azure::Chat
  def completion_url; end
  def format_messages(messages); end
  def format_role(role); end
end
module RubyLLM::Providers::Azure::Embeddings
  def embedding_url(*, **, &); end
  def render_embedding_payload(text, model:, dimensions:); end
  def self.embedding_url(*, **, &); end
  def self.render_embedding_payload(text, model:, dimensions:); end
end
module RubyLLM::Providers::Azure::Media
  def format_content(content); end
  def format_image(image); end
  def self.format_content(content); end
  def self.format_image(image); end
end
module RubyLLM::Providers::Azure::Models
  def models_url; end
end
class RubyLLM::Providers::Bedrock < RubyLLM::Provider
  def api_base; end
  def api_payload(payload); end
  def bedrock_region; end
  def complete(messages, tools:, temperature:, model:, params: nil, headers: nil, schema: nil, thinking: nil, tool_prefs: nil, &); end
  def headers; end
  def list_models; end
  def model_supports_top_k?(model); end
  def normalize_params(params, model:); end
  def parse_error(response); end
  def self.configuration_options; end
  def self.configuration_requirements; end
  def sync_response(connection, payload, additional_headers = nil); end
  include RubyLLM::Providers::Bedrock::Auth
  include RubyLLM::Providers::Bedrock::Chat
  include RubyLLM::Providers::Bedrock::Media
  include RubyLLM::Providers::Bedrock::Models
  include RubyLLM::Providers::Bedrock::Streaming
end
module RubyLLM::Providers::Bedrock::Auth
  def canonical_query_string(raw_query); end
  def canonical_uri(path); end
  def sign_headers(method, path, body, base_url: nil); end
  def signed_get(base_url, url); end
  def signed_post(connection, url, payload, additional_headers = nil); end
  def signing_key(date_stamp); end
  def uri_encode(text); end
end
module RubyLLM::Providers::Bedrock::Chat
  def budget_reasoning_config(thinking); end
  def build_output_config(schema); end
  def completion_url; end
  def default_input_schema; end
  def effort_reasoning_config(thinking); end
  def normalize_tool_result_block(block); end
  def parse_completion_response(response); end
  def parse_reasoning_content_block(block); end
  def parse_text_content(content_blocks); end
  def parse_thinking(content_blocks); end
  def parse_tool_calls(content_blocks); end
  def render_additional_model_request_fields(thinking); end
  def render_inference_config(_model, temperature); end
  def render_message_content(msg); end
  def render_messages(messages); end
  def render_non_tool_message(msg); end
  def render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def render_raw_content(content); end
  def render_raw_tool_result_content(raw_value); end
  def render_reasoning_fields(thinking); end
  def render_role(role); end
  def render_system(messages); end
  def render_thinking_block(thinking); end
  def render_tool(tool); end
  def render_tool_choice(choice); end
  def render_tool_config(tools, tool_prefs); end
  def render_tool_result_block(msg); end
  def render_tool_result_content(content); end
  def sanitize_non_assistant_raw_blocks(blocks); end
  def self.budget_reasoning_config(thinking); end
  def self.build_output_config(schema); end
  def self.completion_url; end
  def self.default_input_schema; end
  def self.effort_reasoning_config(thinking); end
  def self.normalize_tool_result_block(block); end
  def self.parse_completion_response(response); end
  def self.parse_reasoning_content_block(block); end
  def self.parse_text_content(content_blocks); end
  def self.parse_thinking(content_blocks); end
  def self.parse_tool_calls(content_blocks); end
  def self.render_additional_model_request_fields(thinking); end
  def self.render_inference_config(_model, temperature); end
  def self.render_message_content(msg); end
  def self.render_messages(messages); end
  def self.render_non_tool_message(msg); end
  def self.render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def self.render_raw_content(content); end
  def self.render_raw_tool_result_content(raw_value); end
  def self.render_reasoning_fields(thinking); end
  def self.render_role(role); end
  def self.render_system(messages); end
  def self.render_thinking_block(thinking); end
  def self.render_tool(tool); end
  def self.render_tool_choice(choice); end
  def self.render_tool_config(tools, tool_prefs); end
  def self.render_tool_result_block(msg); end
  def self.render_tool_result_content(content); end
  def self.sanitize_non_assistant_raw_blocks(blocks); end
  def self.tool_result_content_block?(block); end
  def tool_result_content_block?(block); end
end
module RubyLLM::Providers::Bedrock::Media
  def empty_content?(content); end
  def render_attachment(attachment, used_document_names:); end
  def render_content(content, used_document_names: nil); end
  def render_content_object(content, used_document_names); end
  def render_document_attachment(attachment, used_document_names:); end
  def render_image_attachment(attachment); end
  def render_raw_content(content); end
  def sanitize_document_name(filename); end
  def self.empty_content?(content); end
  def self.render_attachment(attachment, used_document_names:); end
  def self.render_content(content, used_document_names: nil); end
  def self.render_content_object(content, used_document_names); end
  def self.render_document_attachment(attachment, used_document_names:); end
  def self.render_image_attachment(attachment); end
  def self.render_raw_content(content); end
  def self.sanitize_document_name(filename); end
  def self.unique_document_name(base_name, used_names); end
  def unique_document_name(base_name, used_names); end
end
module RubyLLM::Providers::Bedrock::Models
  def create_model_info(model_data, slug, _capabilities = nil); end
  def model_id_with_region(model_id, model_data); end
  def models_api_base; end
  def models_url; end
  def normalize_inference_profile_id(model_id, inference_types, region); end
  def normalize_modalities(modalities); end
  def parse_capabilities(model_data); end
  def parse_context_window(model_data); end
  def parse_list_models_response(response, slug, _capabilities); end
  def reasoning_embedded?(model); end
  def region_prefix(region); end
  def region_prefixed?(model_id); end
  def self.create_model_info(model_data, slug, _capabilities = nil); end
  def self.model_id_with_region(model_id, model_data); end
  def self.models_api_base; end
  def self.models_url; end
  def self.normalize_inference_profile_id(model_id, inference_types, region); end
  def self.normalize_modalities(modalities); end
  def self.parse_capabilities(model_data); end
  def self.parse_context_window(model_data); end
  def self.parse_list_models_response(response, slug, _capabilities); end
  def self.reasoning_embedded?(model); end
  def self.region_prefix(region); end
  def self.region_prefixed?(model_id); end
  def self.supports_structured_output?(model_id); end
  def self.with_region_prefix(model_id, region); end
  def supports_structured_output?(model_id); end
  def with_region_prefix(model_id, region); end
end
module RubyLLM::Providers::Bedrock::Streaming
  def build_chunk(event); end
  def decode_event_payload(payload); end
  def decode_events(decoder, raw_chunk); end
  def event_stream_decoder; end
  def event_usage(event); end
  def extract_cache_creation_tokens(metadata_usage, usage); end
  def extract_cached_tokens(metadata_usage, usage); end
  def extract_content_delta(event); end
  def extract_input_tokens(metadata_usage, usage, message_usage); end
  def extract_output_tokens(metadata_usage, usage); end
  def extract_reasoning_tokens(metadata_usage, usage); end
  def extract_signature_from_delta(event); end
  def extract_signature_from_start(event); end
  def extract_thinking_delta(event); end
  def extract_thinking_signature(event); end
  def extract_tool_call_delta(event); end
  def extract_tool_call_start(event); end
  def extract_tool_calls(event); end
  def handle_failed_stream(chunk, env); end
  def handle_non_eventstream_error_chunk(raw_chunk); end
  def normalized_delta(event); end
  def parse_stream_chunk(decoder, raw_chunk, accumulator); end
  def raise_stream_error(event); end
  def raise_streaming_chunk_error(payload); end
  def stream_error_event?(event); end
  def stream_response(connection, payload, additional_headers = nil, &block); end
  def stream_url; end
  def tool_call_delta_event?(event); end
  def tool_call_start_event?(event); end
end
class RubyLLM::Providers::DeepSeek < RubyLLM::Providers::OpenAI
  def api_base; end
  def headers; end
  def self.capabilities; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  include RubyLLM::Providers::DeepSeek::Chat
end
module RubyLLM::Providers::DeepSeek::Chat
  def format_role(role); end
  def self.format_role(role); end
end
class RubyLLM::Providers::Gemini < RubyLLM::Provider
  def api_base; end
  def attachment_filename(mime_type, index); end
  def build_file_attachment(file_data, index); end
  def build_inline_attachment(inline_data, index); end
  def build_response_content(parts); end
  def headers; end
  def self.capabilities; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  include RubyLLM::Providers::Gemini::Chat
  include RubyLLM::Providers::Gemini::Embeddings
  include RubyLLM::Providers::Gemini::Images
  include RubyLLM::Providers::Gemini::Media
  include RubyLLM::Providers::Gemini::Models
  include RubyLLM::Providers::Gemini::Streaming
  include RubyLLM::Providers::Gemini::Tools
  include RubyLLM::Providers::Gemini::Transcription
end
module RubyLLM::Providers::Gemini::Chat
  def build_json_schema(schema); end
  def build_thinking_config(_model, thinking); end
  def build_thought_part(thinking); end
  def calculate_output_tokens(data); end
  def completion_url; end
  def convert_schema_to_gemini(schema); end
  def extract_text_parts(parts); end
  def extract_thought_parts(parts); end
  def extract_thought_signature(parts); end
  def extract_version(text); end
  def format_message_parts(msg); end
  def format_messages(messages); end
  def format_parts(msg); end
  def format_role(role); end
  def function_call?(candidate); end
  def gemini_version(model); end
  def model_metadata_value(model, key); end
  def parse_completion_response(response); end
  def parse_content(data); end
  def render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def resolve_budget(thinking); end
  def resolve_effort_level(thinking); end
  def response_json_schema_supported?(model); end
  def safe_string(value); end
  def self.build_thinking_config(_model, thinking); end
  def self.completion_url; end
  def self.render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def self.resolve_budget(thinking); end
  def self.resolve_effort_level(thinking); end
  def structured_output_config(schema, model); end
end
class RubyLLM::Providers::Gemini::Chat::MessageFormatter
  def build_standard_message(message); end
  def build_tool_response(parts); end
  def collect_tool_parts; end
  def current_message; end
  def format; end
  def format_tool_result(message, tool_name); end
  def initialize(messages, format_role:, format_parts:, format_tool_result:); end
  def remember_tool_calls; end
  def tool_message?(message); end
end
class RubyLLM::Providers::Gemini::Chat::GeminiSchema
  def apply_description(target, schema); end
  def build_array(schema, visited_refs); end
  def build_object(schema, visited_refs); end
  def build_scalar(type, schema, allowed_keys); end
  def convert(schema, visited_refs); end
  def copy_attribute(target, source, key); end
  def default_string_schema; end
  def definition_key?(key); end
  def definitions; end
  def initialize(schema); end
  def lookup_definition(ref); end
  def merge_definitions(raw_defs); end
  def normalize_any_of(schema); end
  def resolve_reference(schema, visited_refs); end
  def schema_type(option); end
  def strip_unsupported_keys(schema); end
  def symbolize_and_extract_definitions(value); end
  def to_h; end
end
module RubyLLM::Providers::Gemini::Embeddings
  def embedding_url(model:); end
  def parse_embedding_response(response, model:, text:); end
  def render_embedding_payload(text, model:, dimensions:); end
  def self.embedding_url(model:); end
  def self.parse_embedding_response(response, model:, text:); end
  def self.render_embedding_payload(text, model:, dimensions:); end
  def single_embedding_payload(text, model:, dimensions:); end
end
module RubyLLM::Providers::Gemini::Images
  def images_url; end
  def parse_image_response(response, model:); end
  def render_image_payload(prompt, model:, size:); end
end
module RubyLLM::Providers::Gemini::Models
  def models_url; end
  def parse_list_models_response(response, slug, capabilities); end
  def self.models_url; end
  def self.parse_list_models_response(response, slug, capabilities); end
end
module RubyLLM::Providers::Gemini::Transcription
  def build_generation_config(options); end
  def build_prompt(custom_prompt, language); end
  def extract_text(data); end
  def extract_usage(data); end
  def format_audio_part(attachment); end
  def parse_transcription_response(response, model:); end
  def render_transcription_payload(attachment, language:, **options); end
  def sum_output_tokens(metadata); end
  def transcribe(audio_file, model:, language:, **options); end
  def transcription_url(model); end
end
module RubyLLM::Providers::Gemini::Streaming
  def build_chunk(data); end
  def extract_content(data); end
  def extract_input_tokens(data); end
  def extract_model_id(data); end
  def extract_output_tokens(data); end
  def extract_text_content(parts); end
  def extract_thought_content(parts); end
  def extract_thought_signature(parts); end
  def parse_streaming_error(data); end
  def stream_url; end
end
module RubyLLM::Providers::Gemini::Tools
  def build_tool_config(tool_choice); end
  def convert_property(property_schema); end
  def convert_tool_schema_to_gemini(schema); end
  def copy_common_attributes(target, source); end
  def copy_tool_attributes(target, source, attributes); end
  def extract_tool_calls(data); end
  def forced_tool_choice?(tool_choice); end
  def format_tool_call(msg); end
  def format_tool_result(msg, function_name = nil); end
  def format_tools(tools); end
  def function_declaration_for(tool); end
  def normalize_any_of_schema(schema); end
  def param_type_for_gemini(type); end
  def schema_type(schema); end
  def schema_value(source, attribute); end
  def specific_tool_choice?(tool_choice); end
end
module RubyLLM::Providers::Gemini::Media
  def format_attachment(attachment); end
  def format_content(content); end
  def format_text(text); end
  def format_text_file(text_file); end
  def self.format_attachment(attachment); end
  def self.format_content(content); end
  def self.format_text(text); end
  def self.format_text_file(text_file); end
end
class RubyLLM::Providers::GPUStack < RubyLLM::Providers::OpenAI
  def api_base; end
  def headers; end
  def self.capabilities; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  def self.local?; end
  include RubyLLM::Providers::GPUStack::Chat
  include RubyLLM::Providers::GPUStack::Media
  include RubyLLM::Providers::GPUStack::Models
end
module RubyLLM::Providers::GPUStack::Chat
  def format_messages(messages); end
  def format_role(role); end
  def self.format_messages(messages); end
  def self.format_role(role); end
end
module RubyLLM::Providers::GPUStack::Models
  def build_capabilities(model); end
  def build_modalities(model); end
  def determine_model_type(model); end
  def models_url; end
  def parse_list_models_response(response, slug, _capabilities); end
  def self.models_url; end
  def self.parse_list_models_response(response, slug, _capabilities); end
end
module RubyLLM::Providers::GPUStack::Media
  def format_content(content); end
  def format_image(image); end
  def self.format_content(content); end
  def self.format_image(image); end
  extend RubyLLM::Providers::OpenAI::Media
end
class RubyLLM::Providers::Mistral < RubyLLM::Providers::OpenAI
  def api_base; end
  def headers; end
  def self.capabilities; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  include RubyLLM::Providers::Mistral::Chat
  include RubyLLM::Providers::Mistral::Embeddings
  include RubyLLM::Providers::Mistral::Models
end
module RubyLLM::Providers::Mistral::Chat
  def append_formatted_content(content_blocks, formatted_content); end
  def build_thinking_blocks(thinking); end
  def format_content_with_thinking(msg); end
  def format_messages(messages); end
  def format_role(role); end
  def render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def self.append_formatted_content(content_blocks, formatted_content); end
  def self.build_thinking_blocks(thinking); end
  def self.format_content_with_thinking(msg); end
  def self.format_messages(messages); end
  def self.format_role(role); end
  def self.render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def self.warn_on_unsupported_thinking(model, thinking); end
  def warn_on_unsupported_thinking(model, thinking); end
end
module RubyLLM::Providers::Mistral::Models
  def headers(config); end
  def models_url; end
  def parse_list_models_response(response, slug, capabilities); end
  def self.headers(config); end
  def self.models_url; end
  def self.parse_list_models_response(response, slug, capabilities); end
end
module RubyLLM::Providers::Mistral::Embeddings
  def embedding_url(*, **, &); end
  def parse_embedding_response(response, model:, text:); end
  def render_embedding_payload(text, model:, dimensions:); end
  def self.embedding_url(*, **, &); end
  def self.parse_embedding_response(response, model:, text:); end
  def self.render_embedding_payload(text, model:, dimensions:); end
end
class RubyLLM::Providers::Ollama < RubyLLM::Providers::OpenAI
  def api_base; end
  def headers; end
  def self.capabilities; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  def self.local?; end
  include RubyLLM::Providers::Ollama::Chat
  include RubyLLM::Providers::Ollama::Media
  include RubyLLM::Providers::Ollama::Models
end
module RubyLLM::Providers::Ollama::Chat
  def format_messages(messages); end
  def format_role(role); end
  def self.format_messages(messages); end
  def self.format_role(role); end
end
module RubyLLM::Providers::Ollama::Media
  def format_content(content); end
  def format_image(image); end
  def self.format_content(content); end
  def self.format_image(image); end
  extend RubyLLM::Providers::OpenAI::Media
end
module RubyLLM::Providers::Ollama::Models
  def models_url; end
  def parse_list_models_response(response, slug, _capabilities); end
end
class RubyLLM::Providers::OpenRouter < RubyLLM::Providers::OpenAI
  def api_base; end
  def headers; end
  def parse_error(response); end
  def parse_error_part_message(part); end
  def self.configuration_options; end
  def self.configuration_requirements; end
  include RubyLLM::Providers::OpenRouter::Chat
  include RubyLLM::Providers::OpenRouter::Images
  include RubyLLM::Providers::OpenRouter::Models
  include RubyLLM::Providers::OpenRouter::Streaming
end
module RubyLLM::Providers::OpenRouter::Chat
  def build_reasoning(thinking); end
  def extract_thinking_signature(message_data); end
  def extract_thinking_text(message_data); end
  def format_messages(messages); end
  def format_role(role); end
  def format_thinking(msg); end
  def parse_completion_response(response); end
  def render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
  def self.build_reasoning(thinking); end
  def self.extract_thinking_signature(message_data); end
  def self.extract_thinking_text(message_data); end
  def self.format_messages(messages); end
  def self.format_role(role); end
  def self.format_thinking(msg); end
  def self.parse_completion_response(response); end
  def self.render_payload(messages, tools:, temperature:, model:, stream: nil, schema: nil, thinking: nil, tool_prefs: nil); end
end
module RubyLLM::Providers::OpenRouter::Models
  def models_url; end
  def parse_list_models_response(response, slug, _capabilities); end
  def self.models_url; end
  def self.parse_list_models_response(response, slug, _capabilities); end
  def self.supported_parameters_to_capabilities(params); end
  def supported_parameters_to_capabilities(params); end
end
module RubyLLM::Providers::OpenRouter::Streaming
  def build_chunk(data); end
  def extract_thinking_signature(delta); end
  def extract_thinking_text(delta); end
  def parse_streaming_error(data); end
  def self.build_chunk(data); end
  def self.extract_thinking_signature(delta); end
  def self.extract_thinking_text(delta); end
  def self.parse_streaming_error(data); end
  def self.stream_url; end
  def stream_url; end
end
module RubyLLM::Providers::OpenRouter::Images
  def build_image_from_url(image_url, model); end
  def images_url; end
  def parse_image_response(response, model:); end
  def render_image_payload(prompt, model:, size:); end
  def self.build_image_from_url(image_url, model); end
  def self.images_url; end
  def self.parse_image_response(response, model:); end
  def self.render_image_payload(prompt, model:, size:); end
end
class RubyLLM::Providers::Perplexity < RubyLLM::Providers::OpenAI
  def api_base; end
  def headers; end
  def parse_error(response); end
  def self.capabilities; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  include RubyLLM::Providers::Perplexity::Chat
  include RubyLLM::Providers::Perplexity::Models
end
module RubyLLM::Providers::Perplexity::Chat
  def format_role(role); end
  def self.format_role(role); end
end
module RubyLLM::Providers::Perplexity::Models
  def create_model_info(id, slug, capabilities); end
  def list_models(**); end
  def parse_list_models_response(_response, slug, capabilities); end
end
class RubyLLM::Providers::VertexAI < RubyLLM::Providers::Gemini
  def api_base; end
  def headers; end
  def initialize(config); end
  def initialize_authorizer; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  include RubyLLM::Providers::VertexAI::Chat
  include RubyLLM::Providers::VertexAI::Embeddings
  include RubyLLM::Providers::VertexAI::Models
  include RubyLLM::Providers::VertexAI::Streaming
  include RubyLLM::Providers::VertexAI::Transcription
end
module RubyLLM::Providers::VertexAI::Chat
  def completion_url; end
end
module RubyLLM::Providers::VertexAI::Streaming
  def stream_url; end
end
module RubyLLM::Providers::VertexAI::Embeddings
  def embedding_url(model:); end
  def parse_embedding_response(response, model:, text:); end
  def render_embedding_payload(text, model:, dimensions:); end
  def self.embedding_url(model:); end
  def self.parse_embedding_response(response, model:, text:); end
  def self.render_embedding_payload(text, model:, dimensions:); end
end
module RubyLLM::Providers::VertexAI::Models
  def build_known_models; end
  def build_model_from_api_data(model_data, model_id); end
  def determine_model_family(model_id); end
  def extract_capabilities(model_data); end
  def extract_model_id_from_path(path); end
  def list_models; end
end
module RubyLLM::Providers::VertexAI::Transcription
  def transcription_url(model); end
end
class RubyLLM::Providers::XAI < RubyLLM::Providers::OpenAI
  def api_base; end
  def headers; end
  def self.configuration_options; end
  def self.configuration_requirements; end
  include RubyLLM::Providers::XAI::Chat
  include RubyLLM::Providers::XAI::Models
end
module RubyLLM::Providers::XAI::Chat
  def format_role(role); end
end
module RubyLLM::Providers::XAI::Models
  def capabilities_for(model_id); end
  def format_display_name(model_id); end
  def modalities_for(model_id); end
  def parse_list_models_response(response, slug, _capabilities); end
  def self.capabilities_for(model_id); end
  def self.format_display_name(model_id); end
  def self.modalities_for(model_id); end
  def self.parse_list_models_response(response, slug, _capabilities); end
end
class RubyLLM::Railtie < Rails::Railtie
end
module RubyLLM::ActiveRecord
end
module RubyLLM::ActiveRecord::ActsAs
  def self.included(base); end
  extend ActiveSupport::Concern
end
module RubyLLM::ActiveRecord::ActsAs::ClassMethods
  def acts_as_chat(messages: nil, message_class: nil, messages_foreign_key: nil, model: nil, model_class: nil, model_foreign_key: nil); end
  def acts_as_message(chat: nil, chat_class: nil, chat_foreign_key: nil, touch_chat: nil, tool_calls: nil, tool_call_class: nil, tool_calls_foreign_key: nil, model: nil, model_class: nil, model_foreign_key: nil); end
  def acts_as_model(chats: nil, chat_class: nil, chats_foreign_key: nil); end
  def acts_as_tool_call(message: nil, message_class: nil, message_foreign_key: nil, result: nil, result_class: nil, result_foreign_key: nil); end
end
module RubyLLM::ActiveRecord::ActsAsLegacy
  extend ActiveSupport::Concern
end
module RubyLLM::ActiveRecord::ActsAsLegacy::ClassMethods
  def acts_as_chat(message_class: nil, tool_call_class: nil); end
  def acts_as_message(chat_class: nil, chat_foreign_key: nil, tool_call_class: nil, tool_call_foreign_key: nil, touch_chat: nil); end
  def acts_as_tool_call(message_class: nil, message_foreign_key: nil, result_foreign_key: nil); end
end
module RubyLLM::ActiveRecord::ChatLegacyMethods
  def add_message(message_or_attributes); end
  def append_instructions?(append:, replace:); end
  def ask(message = nil, with: nil, &); end
  def build_content(message, attachments); end
  def cleanup_failed_messages; end
  def cleanup_orphaned_tool_results; end
  def complete(*, **, &); end
  def content_like?(object); end
  def convert_to_active_storage_format(source); end
  def create_user_message(content, with: nil); end
  def find_tool_call_id(tool_call_id); end
  def on_end_message(&block); end
  def on_new_message(&block); end
  def on_tool_call(*, **, &); end
  def on_tool_result(*, **, &); end
  def order_messages_for_llm(messages); end
  def persist_content(message_record, attachments); end
  def persist_message_completion(message); end
  def persist_new_message; end
  def persist_system_instruction(instructions, append:); end
  def persist_tool_calls(tool_calls, message_record: nil); end
  def prepare_content_for_storage(content); end
  def prepare_for_active_storage(attachments); end
  def reapply_runtime_instructions(chat); end
  def replace_persisted_system_instructions(instructions); end
  def runtime_instructions; end
  def say(message = nil, with: nil, &); end
  def setup_persistence_callbacks; end
  def store_runtime_instruction(instructions, append:); end
  def to_llm(context: nil); end
  def with_context(context); end
  def with_headers(*, **, &); end
  def with_instructions(instructions, append: nil, replace: nil); end
  def with_model(*, **, &); end
  def with_params(*, **, &); end
  def with_runtime_instructions(instructions, append: nil, replace: nil); end
  def with_schema(*, **, &); end
  def with_temperature(*, **, &); end
  def with_tool(*, **, &); end
  def with_tools(*, **, &); end
  extend ActiveSupport::Concern
end
module RubyLLM::ActiveRecord::ChatLegacyMethods::ClassMethods
  def tool_call_class; end
end
module RubyLLM::ActiveRecord::MessageLegacyMethods
  def download_attachment(attachment); end
  def extract_content; end
  def extract_tool_call_id; end
  def extract_tool_calls; end
  def to_llm; end
  extend ActiveSupport::Concern
end
module RubyLLM::ActiveRecord::MessageLegacyMethods::ClassMethods
  def chat_class; end
  def chat_foreign_key; end
  def tool_call_class; end
  def tool_call_foreign_key; end
end
