# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/serpapi/all/serpapi.rbi
#
# serpapi-1.0.3

module SerpApi
end
class SerpApi::SerpApiError < StandardError
  def decoder; end
  def initialize(message = nil, serpapi_error: nil, search_params: nil, response_status: nil, search_id: nil, decoder: nil); end
  def response_status; end
  def search_id; end
  def search_params; end
  def serpapi_error; end
  def to_h; end
  def validate_optional_integer(value, name = nil); end
  def validate_optional_string(value, name = nil); end
  def validate_optional_symbol(value, name = nil); end
end
class SerpApi::Client
  def account(api_key = nil); end
  def api_key; end
  def close; end
  def engine; end
  def execute_request(endpoint, params); end
  def get(endpoint, decoder = nil, params = nil); end
  def handle_response(response, decoder, endpoint, params); end
  def html(params = nil); end
  def initialize(params = nil); end
  def inspect; end
  def location(params = nil); end
  def params; end
  def persistent; end
  def persistent?; end
  def process_html_response(response, endpoint, params); end
  def process_json_response(response, endpoint, params); end
  def query(params); end
  def raise_http_error(response, data, endpoint, params, explicit_error: nil, decoder: nil); end
  def raise_parser_error(response, endpoint, params); end
  def search(params = nil); end
  def search_archive(search_id, format = nil); end
  def socket; end
  def timeout; end
  def validate_json_content!(data, response, endpoint, params); end
end
