# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `serpapi` gem.
# Please instead update this file by running `bin/tapioca gem serpapi`.


# Ruby client for SerpApi.com
#  Scrape results for all major search engines from our fast, easy, and complete API.
# Client implementation for SerpApi.com
#
# Module includes SerpApi error handling.
#
# pkg:gem/serpapi#lib/serpapi.rb:3
module SerpApi; end

# Client for SerpApi.com
# powered by HTTP.rb
#
#  features:
#  * async non-block search
#  * persistent HTTP connection
#  * search API
#  * location API
#  * account API
#  * search archive API
#
# pkg:gem/serpapi#lib/serpapi/client.rb:15
class SerpApi::Client
  # Constructor
  # The `Serpapi::Client` constructor takes a hash of options as input.
  #
  # **Example:**
  #
  # ```ruby
  # require 'serpapi'
  #
  # client = SerpApi::Client.new(
  #   api_key: "secure API key",
  #   engine: "google",
  #   timeout: 30,
  #   persistent: true
  # )
  #
  # result = client.search(q: "coffee")
  #
  # client.close
  # ```
  #
  # **Parameters:**
  #
  # * `api_key`: [String] User secret API key.
  # * `engine`: [String] Search engine selected.
  # * `persistent`: [Boolean] Keep socket connection open to save on SSL handshake / connection reconnectino (2x
  # faster). [default: true]
  # * `async`: [Boolean] Support non-blocking job submission. [default: false]
  # * `timeout`: [Integer] HTTP get max timeout in seconds [default: 120s == 2m]
  # * `symbolize_names`: [Boolean] Convert JSON keys to symbols. [default: true]
  #
  # **Key:**kr
  #
  # The `key` parameter can be either a symbol or a string.
  #
  # **Note:**
  #
  # * All parameters are optional.
  # * The `close` method should be called when the client is no longer needed.
  #
  # @param [Hash] params default for the search
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:69
  def initialize(params = T.unsafe(nil)); end

  # Get account information using Account API
  #
  # example: spec/serpapi/client/account_api_spec.rb
  # doc: https://serpapi.com/account-api
  #
  # @param [String] api_key secret key [optional if already provided to the constructor]
  # @return [Hash] account information
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:164
  def account(api_key = T.unsafe(nil)); end

  # @return [String] api_key user secret API key as provided to the constructor
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:175
  def api_key; end

  # close open connection if active
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:180
  def close; end

  # @return [String] default search engine
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:170
  def engine; end

  # html search perform a search using SerpApi.com
  #  the output is raw HTML from the search engine.
  #  it is useful for training AI models, RAG, debugging
  #   or when you need to parse the HTML yourself.
  #
  # @return [String] raw html search results directly from the search engine.
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:122
  def html(params = T.unsafe(nil)); end

  # pkg:gem/serpapi#lib/serpapi/client.rb:184
  def inspect; end

  # Get location using Location API
  #
  # example: spec/serpapi/location_api_spec.rb
  # doc: https://serpapi.com/locations-api
  #
  # @param [Hash] params must includes fields: q, limit
  # @return [Array<Hash>] list of matching locations
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:133
  def location(params = T.unsafe(nil)); end

  # HTTP timeout requests
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:20
  def params; end

  # HTTP timeout requests
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:20
  def persistent; end

  # perform a search using SerpApi.com
  #
  # see: https://serpapi.com/search-api
  #
  # note that the raw response
  #                 from the search engine is converted to JSON by SerpApi.com backend.
  #                 thus, most of the compute power is on the backsdend and not on the client side.
  # @param [Hash] params includes engine, api_key, search fields and more..
  #                this override the default params provided to the constructor.
  # @return [Hash] search results formatted as a Hash.
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:112
  def search(params = T.unsafe(nil)); end

  # Retrieve search result from the Search Archive API
  #
  # ```ruby
  # client = SerpApi::Client.new(engine: 'google', api_key: ENV['SERPAPI_KEY'])
  # results = client.search(q: 'Coffee', location: 'Portland')
  # search_id = results[:search_metadata][:id]
  # archive_search = client.search_archive(search_id)
  # ```
  # example: spec/serpapi/client/search_archive_api_spec.rb
  # doc: https://serpapi.com/search-archive-api
  #
  # @param [String|Integer] search_id from original search `results[:search_metadata][:id]`
  # @param [Symbol] format :json or :html [default: json, optional]
  # @return [String|Hash] raw html or JSON / Hash
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:151
  def search_archive(search_id, format = T.unsafe(nil)); end

  # HTTP timeout requests
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:20
  def socket; end

  # HTTP timeout requests
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:20
  def timeout; end

  private

  # pkg:gem/serpapi#lib/serpapi/client.rb:222
  def execute_request(endpoint, params); end

  # Perform HTTP GET request to the SerpApi.com backend endpoint.
  #
  # @param [String] endpoint HTTP service URI
  # @param [Symbol] decoder type :json or :html
  # @param [Hash] params custom search inputs
  # @return [String|Hash] raw HTML or decoded response as JSON / Hash
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:217
  def get(endpoint, decoder = T.unsafe(nil), params = T.unsafe(nil)); end

  # pkg:gem/serpapi#lib/serpapi/client.rb:231
  def handle_response(response, decoder, endpoint, params); end

  # @return [Boolean] HTTP session persistent enabled
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:207
  def persistent?; end

  # pkg:gem/serpapi#lib/serpapi/client.rb:256
  def process_html_response(response, endpoint, params); end

  # pkg:gem/serpapi#lib/serpapi/client.rb:242
  def process_json_response(response, endpoint, params); end

  # @param [Hash] params to merge with default parameters provided to the constructor.
  # @return [Hash] merged query parameters after cleanup
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:193
  def query(params); end

  # Centralized error raising to clean up the logic methods
  #
  # pkg:gem/serpapi#lib/serpapi/client.rb:270
  def raise_http_error(response, data, endpoint, params, explicit_error: T.unsafe(nil), decoder: T.unsafe(nil)); end

  # pkg:gem/serpapi#lib/serpapi/client.rb:284
  def raise_parser_error(response, endpoint, params); end

  # pkg:gem/serpapi#lib/serpapi/client.rb:261
  def validate_json_content!(data, response, endpoint, params); end
end

# Backend service URL
#
# pkg:gem/serpapi#lib/serpapi/client.rb:17
SerpApi::Client::BACKEND = T.let(T.unsafe(nil), String)

# Custom error class for SerpApi-related errors.
# Inherits from StandardError.
# Includes optional attributes for detailed error context.
# Attributes:
# - serpapi_error: String error message from SerpApi (optional)
# - search_params: Hash of search parameters used (optional)
# - response_status: Integer HTTP or response status code (optional)
# - search_id: String id returned by the service for the search (optional)
# - decoder: Symbol representing the decoder/format used (optional) (e.g. :json)
#
# pkg:gem/serpapi#lib/serpapi/error.rb:14
class SerpApi::SerpApiError < ::StandardError
  # All attributes are optional keyword arguments.
  #
  # @param message [String, nil] an optional human message passed to StandardError
  # @param serpapi_error [String, nil] optional error string coming from SerpAPI
  # @param search_params [Hash, nil] optional hash of the search parameters used
  # @param response_status [Integer, nil] optional HTTP or response status code
  # @param search_id [String, nil] optional id returned by the service for the search
  # @param decoder [Symbol, nil] optional decoder/format used (e.g. :json)
  #
  # pkg:gem/serpapi#lib/serpapi/error.rb:25
  def initialize(message = T.unsafe(nil), serpapi_error: T.unsafe(nil), search_params: T.unsafe(nil), response_status: T.unsafe(nil), search_id: T.unsafe(nil), decoder: T.unsafe(nil)); end

  # pkg:gem/serpapi#lib/serpapi/error.rb:15
  def decoder; end

  # pkg:gem/serpapi#lib/serpapi/error.rb:15
  def response_status; end

  # pkg:gem/serpapi#lib/serpapi/error.rb:15
  def search_id; end

  # pkg:gem/serpapi#lib/serpapi/error.rb:15
  def search_params; end

  # pkg:gem/serpapi#lib/serpapi/error.rb:15
  def serpapi_error; end

  # Return a compact hash representation (omits nil values).
  #
  # @return [Hash]
  #
  # pkg:gem/serpapi#lib/serpapi/error.rb:43
  def to_h; end

  private

  # pkg:gem/serpapi#lib/serpapi/error.rb:63
  def validate_optional_integer(value, name = T.unsafe(nil)); end

  # pkg:gem/serpapi#lib/serpapi/error.rb:56
  def validate_optional_string(value, name = T.unsafe(nil)); end

  # pkg:gem/serpapi#lib/serpapi/error.rb:75
  def validate_optional_symbol(value, name = T.unsafe(nil)); end
end

# Current version of the gem
#
# pkg:gem/serpapi#lib/serpapi/version.rb:3
SerpApi::VERSION = T.let(T.unsafe(nil), String)
