# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/webmock/all/webmock.rbi
#
# webmock-3.26.2

module WebMock
  extend WebMock::API
  include WebMock::API
end
class WebMock::Deprecation
end
class WebMock::NetConnectNotAllowedError < Exception
end
module WebMock::Util
end
class WebMock::Util::QueryMapper
end
class WebMock::Util::URI
end
module WebMock::Util::URI::CharacterClasses
end
class WebMock::Util::Headers
end
class WebMock::Util::HashCounter
end
class WebMock::Util::HashKeysStringifier
end
class WebMock::Util::ValuesStringifier
end
module WebMock::Util::Parsers
end
class WebMock::Util::Parsers::ParseError < StandardError
end
class WebMock::Util::Parsers::JSON
end
class WebMock::Util::Parsers::XML
end
class WebMock::VersionChecker
end
class WebMock::HashValidator
end
module WebMock::Matchers
end
class WebMock::Matchers::HashArgumentMatcher
end
class WebMock::Matchers::HashExcludingMatcher < WebMock::Matchers::HashArgumentMatcher
end
class WebMock::Matchers::HashIncludingMatcher < WebMock::Matchers::HashArgumentMatcher
end
class WebMock::Matchers::AnyArgMatcher
end
module WebMock::RSpecMatcherDetector
end
class WebMock::RequestPattern
end
class WebMock::MethodPattern
end
class WebMock::URIPattern
  include WebMock::RSpecMatcherDetector
end
class WebMock::URICallablePattern < WebMock::URIPattern
end
class WebMock::URIRegexpPattern < WebMock::URIPattern
end
class WebMock::URIAddressablePattern < WebMock::URIPattern
end
class WebMock::URIStringPattern < WebMock::URIPattern
end
class WebMock::BodyPattern
  include WebMock::RSpecMatcherDetector
end
class WebMock::HeadersPattern
end
class WebMock::RequestSignature
end
class WebMock::ResponsesSequence
end
class WebMock::RequestStub
end
class WebMock::ResponseFactory
end
class WebMock::Response
end
class WebMock::Response::InvalidBody < StandardError
end
class WebMock::DynamicResponse < WebMock::Response
end
class WebMock::RackResponse < WebMock::Response
end
class WebMock::StubRequestSnippet
end
class WebMock::RequestSignatureSnippet
end
class WebMock::RequestBodyDiff
end
class WebMock::AssertionFailure
end
class WebMock::RequestExecutionVerifier
end
class WebMock::Config
  extend Singleton::SingletonClassMethods
  include Singleton
end
class WebMock::CallbackRegistry
end
class WebMock::RequestRegistry
  extend Singleton::SingletonClassMethods
  include Singleton
end
class WebMock::StubRegistry
  extend Singleton::SingletonClassMethods
  include Singleton
end
module WebMock::API
  extend WebMock::API
end
class WebMock::HttpLibAdapterRegistry
  extend Singleton::SingletonClassMethods
  include Singleton
end
class WebMock::HttpLibAdapter
end
module Net
end
module Net::WebMockHTTPResponse
end
module WebMock::HttpLibAdapters
end
class WebMock::HttpLibAdapters::NetHttpAdapter < WebMock::HttpLibAdapter
end
class StubSocket
end
class StubSocket::StubIO
end
module WebMock::NetHTTPUtility
end
module HTTP
end
class HTTP::Client
end
class HTTP::Request
end
class HTTP::Response
end
class HTTP::Response::Streamer
end
class HTTP::WebMockPerform
end
class WebMock::HttpLibAdapters::HttpRbAdapter < WebMock::HttpLibAdapter
end
class WebMock::RequestPatternMatcher
end
class WebMock::WebMockMatcher
end
